from __future__ import annotations

from geneset_extractors.preprocessing.rnaseq.de_prepare import run_de_prepare


def run(args) -> dict[str, object]:
    return run_de_prepare(
        modality=args.modality,
        counts_tsv=args.counts_tsv,
        out_dir=args.out_dir,
        organism=args.organism,
        genome_build=args.genome_build,
        matrix_orientation=args.matrix_orientation,
        feature_id_column=args.feature_id_column,
        matrix_delim=args.matrix_delim,
        metadata_delim=args.metadata_delim,
        sample_id_column=getattr(args, "sample_id_column", None),
        sample_metadata_tsv=getattr(args, "sample_metadata_tsv", None),
        subject_metadata_tsv=getattr(args, "subject_metadata_tsv", None),
        subject_join_sample_column=getattr(args, "subject_join_sample_column", None),
        subject_join_metadata_column=getattr(args, "subject_join_metadata_column", None),
        subject_column=getattr(args, "subject_column", None),
        cell_id_column=getattr(args, "cell_id_column", None),
        cell_metadata_tsv=getattr(args, "cell_metadata_tsv", None),
        donor_column=getattr(args, "donor_column", None),
        cell_type_column=getattr(args, "cell_type_column", None),
        pseudobulk_within_cell_type=bool(getattr(args, "pseudobulk_within_cell_type", True)),
        min_cells_per_pseudobulk=int(getattr(args, "min_cells_per_pseudobulk", 10)),
        min_donors_per_group=int(getattr(args, "min_donors_per_group", 2)),
        group_column=getattr(args, "group_column", None),
        comparison_mode=getattr(args, "comparison_mode", None),
        condition_a=getattr(args, "condition_a", None),
        condition_b=getattr(args, "condition_b", None),
        reference_level=getattr(args, "reference_level", None),
        comparisons_tsv=getattr(args, "comparisons_tsv", None),
        stratify_by=getattr(args, "stratify_by", None),
        covariates=getattr(args, "covariates", None),
        batch_columns=getattr(args, "batch_columns", None),
        repeated_measures=bool(getattr(args, "repeated_measures", False)),
        allow_approximate_repeated_measures=bool(getattr(args, "allow_approximate_repeated_measures", False)),
        backend=getattr(args, "backend", "auto"),
        allow_non_count_input=bool(getattr(args, "allow_non_count_input", False)),
        write_pseudobulk_artifacts=bool(getattr(args, "write_pseudobulk_artifacts", True)),
        run_extractor=bool(getattr(args, "run_extractor", False)),
        extractor_out_dir=getattr(args, "extractor_out_dir", None),
        extractor_signature_name=getattr(args, "extractor_signature_name", None),
        extractor_score_mode=getattr(args, "extractor_score_mode", "auto"),
        extractor_select=getattr(args, "extractor_select", "top_k"),
        extractor_top_k=int(getattr(args, "extractor_top_k", 200)),
        extractor_quantile=float(getattr(args, "extractor_quantile", 0.01)),
        extractor_min_score=float(getattr(args, "extractor_min_score", 0.0)),
        extractor_normalize=getattr(args, "extractor_normalize", "within_set_l1"),
        extractor_padj_max=getattr(args, "extractor_padj_max", None),
        extractor_pvalue_max=getattr(args, "extractor_pvalue_max", None),
        extractor_min_abs_logfc=getattr(args, "extractor_min_abs_logfc", None),
        extractor_emit_gmt=bool(getattr(args, "extractor_emit_gmt", True)),
        extractor_gmt_split_signed=bool(getattr(args, "extractor_gmt_split_signed", True)),
        extractor_gmt_topk_list=getattr(args, "extractor_gmt_topk_list", "200"),
        extractor_gmt_min_genes=int(getattr(args, "extractor_gmt_min_genes", 100)),
        extractor_gmt_max_genes=int(getattr(args, "extractor_gmt_max_genes", 500)),
    )
