"""Compatibility imports for CLI-facing converter entrypoints."""

from geneset_extractors.extractors.converters import (
    atac_bulk,
    atac_bulk_matrix,
    atac_sc_10x,
    calr_ontology_mapper,
    calr_profile_query,
    chipseq_peak,
    cnv_gene_extractor,
    drug_response_screen,
    methylation_cpg_diff,
    methylation_dmr,
    methylation_dmr_regions,
    morphology_profile_query,
    proteomics_diff,
    ptm_site_diff,
    ptm_site_matrix,
    rna_deg,
    rna_deg_multi,
    rna_sc_programs,
    sc_rna_marker,
)

__all__ = [
    "atac_bulk",
    "atac_bulk_matrix",
    "atac_sc_10x",
    "calr_ontology_mapper",
    "calr_profile_query",
    "chipseq_peak",
    "cnv_gene_extractor",
    "drug_response_screen",
    "methylation_cpg_diff",
    "methylation_dmr",
    "methylation_dmr_regions",
    "morphology_profile_query",
    "proteomics_diff",
    "ptm_site_diff",
    "ptm_site_matrix",
    "rna_deg",
    "rna_deg_multi",
    "rna_sc_programs",
    "sc_rna_marker",
]
